### ISSUE TITLE
FE: Profile Settings > Profile Photo

### ISSUE THREAD

**Issue by rajivtitus** [hatchways/team-gingerbread#51]
Creating the UI for the uploading/deleting profile photo under profile settings

**Comment by ababber** [comment]
Does editing the profile photo mean more than just deleting it?

**Comment by rajivtitus** [comment]
> Does editing the profile photo mean more than just deleting it? For instance, would photo editing features like cropping, filters, etc be part of editing the profile photo?

Editing the profile photo only refers to deleting it, I've updated the wording in the ticket 😃
